name = "Create Postal"
author = "tizu, ChocoNeosome"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd7056d42350455de096348e11a264bd3f5dd2ac9150fdb9a887a01dcb58829a"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
