name = "Create Postal"
author = "tizu, ChocoNeosome"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eabdb4fe9911fffbb0af349df9e53122a2b1997ddac3c54ff36e1eb9afc486dd"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
