name: Build pack on push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: Install packwiz
        run: |
          go install github.com/packwiz/packwiz@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH
      - name: Build pack
        run: packwiz cf export -o pack.zip
      - name: Upload pack artifact
        uses: actions/upload-artifact@v4
        with:
          name: pack
          path: pack.zip
